steps:
- name: 'bash'
  args: ['echo', 'Hello world!']
logsBucket: 'gs://cloudbuild-test-prem'
serviceAccount: 'projects/bamboo-weft-341407/serviceAccounts/test-hd@bamboo-weft-341407.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY
